### ISSUE TITLE
throwed java.util.regex.PatternSyntaxException for run on windows

### ISSUE THREAD

**Issue by rocbin** [lwhite1/tablesaw#86]
Hello!
I first test your demo on my windows 10 compute, that has an error:

Exception in thread "main" java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.compile(Pattern.java:1702)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at com.rocbin.tablesaw.study.LargeDataTest.main(LargeDataTest.java:32)

this error at com.github.lwhite1.tablesaw.store.StorageManager.java in LINE-40.

cause is : 
windows platform, File.separator must be  '\', haha, do you tested on windows?

fixed:

`private static final Pattern SEPARATOR_PATTERN = "\\".equals(File.separator) ? Pattern.compile("\\\\") : Pattern.compile(File.separator);`

**Comment by lwhite1** [comment]
closing. Fixed on master. Fix will be available via maven central after next deployment there.
